project:
  type: website

website:
  title: "JAKes' Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/justicekessie
      - icon: twitter
        href: https://x.com/jakes_officio
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

